import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { CategoryService } from '../../../core/services/category.service';
import { TransactionService } from '../../../core/services/transaction.service';
import { Category } from '../../../core/services/parse-text.service';
import { ModalStatusComponent } from '../../../shared/components/modals/modal-status/modal-status.component';
import { UserService } from '../../../core/services/user.service';

interface EditableCategory extends Category {
    isNew?: boolean;
    markedForDeletion?: boolean;
}

interface EditableTransaction {
    id: string;
    amount: number;
    category: number;
    description: string;
    date: string;
    type: 'income' | 'expense';
    user: string;
}

@Component({
    selector: 'app-transactions-manual',
    standalone: true,
    imports: [CommonModule, FormsModule, ModalStatusComponent],
    templateUrl: './transactions-manual.component.html',
    styleUrls: ['./transactions-manual.component.scss']
})
export class TransactionsManualComponent implements OnInit {
    editableTransactions: EditableTransaction[] = [];
    availableCategories: EditableCategory[] = [];
    existingCategories: Category[] = [];

    isProcessing = false;
    errorMessage = '';

    showModal = signal(false);
    modalType = signal<'success' | 'error'>('success');
    modalMessage = signal('');
    modalImage = signal('');

    constructor(
        private categoryService: CategoryService,
        private transactionService: TransactionService,
        private userService: UserService,
        private router: Router
    ) { }

    async ngOnInit() {
        try {
            this.existingCategories = await this.categoryService.getCategories().toPromise() || [];
            this.initManualMode();
        } catch (error) {
            console.error('Error loading categories:', error);
        }
    }

    initManualMode() {
        this.availableCategories = this.existingCategories.map(cat => ({
            ...cat,
            isNew: false,
            markedForDeletion: false
        }));

        if (this.editableTransactions.length === 0) {
            this.addManualTransaction();
        }
    }

    addManualTransaction() {
        const newTransaction: EditableTransaction = {
            id: `manual-${Date.now()}`,
            amount: 0,
            category: this.availableCategories.length > 0 ? this.availableCategories[0].id : 0,
            description: '',
            date: new Date().toISOString().split('T')[0],
            type: 'expense',
            user: ''
        };

        this.editableTransactions.push(newTransaction);
    }

    removeTransaction(id: string) {
        this.editableTransactions = this.editableTransactions.filter(t => t.id !== id);
    }

    trackByTransactionId(index: number, transaction: EditableTransaction): string {
        return transaction.id;
    }

    async saveAllTransactions() {
        if (this.editableTransactions.length === 0) return;

        this.isProcessing = true;
        this.errorMessage = '';

        try {
            // Remove id from transactions as it is generated by backend
            const cleanTransactions = this.editableTransactions.map(({ id, ...trans }) => ({
                ...trans,
                aiCategorySuggestion: '', // Add missing property required by backend if needed, or adjust interface
                user: this.userService.getCurrentUserUUID()
            }));
            console.log(cleanTransactions);

            try {
                await this.transactionService.createManyTransactions(cleanTransactions as any);

                this.openModal('success', 'Datos registrados correctamente.');
                this.resetForm();
            } catch (error) {
                console.error(error);
                this.openModal('error', 'Ocurrió un error al insertar los datos.');
            }
        } catch (error: any) {
            console.error('Error saving transactions:', error);
            this.errorMessage = error.error?.message || 'Error al guardar.';
        } finally {
            this.isProcessing = false;
        }
    }

    resetForm() {
        this.editableTransactions = [];
        this.initManualMode();
    }

    cancelEdit() {
        this.resetForm();
    }

    openModal(type: 'success' | 'error', message: string): void {
        this.modalType.set(type);
        this.modalMessage.set(message);
        this.showModal.set(true);
    }

    onModalClose(): void {
        this.showModal.set(false);
        this.router.navigate(['dashboard/transactions']);
    }
}
