import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  ManyToOne,
  CreateDateColumn,
  JoinColumn,
} from 'typeorm';
import { User } from '../../user/entities/user.entity';
import { ApiProperty } from '@nestjs/swagger';

@Entity('insights')
export class Insight {
  @ApiProperty({ example: '8d1a35a5-f2b3-4a28-ae9f-cc5b96c18291' })
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ManyToOne(() => User, { nullable: false })
  @JoinColumn({ name: 'user_id' })
  @ApiProperty({ description: 'User associated with this insight.' })
  user: User;

  @ApiProperty({ example: 10, description: 'Month of the insight (1–12).' })
  @Column({ type: 'int' })
  month: number;

  @ApiProperty({ example: 2025, description: 'Year of the insight.' })
  @Column({ type: 'int' })
  year: number;

  @ApiProperty({
    example: 'You overspent in food category this month.',
    description: 'Summary text generated by AI or system.',
  })
  @Column({ type: 'text' })
  summary: string;

  @ApiProperty({
    example: 85,
    description: 'Spending score (0–100) representing financial behavior.',
  })
  @Column({ type: 'smallint' })
  spending_score: number;

  @ApiProperty({
    example: '2025-10-27T13:00:00.000Z',
    description: 'Date when the insight was created.',
  })
  @CreateDateColumn({ type: 'timestamp' })
  created_at: Date;
}
